export const items = [
  {
    c: 'ITEM_1',
    name: 'pintoora gum',
    cost: 24.25,
    costPerPiece: 1.1546391752577319,
    sellingPricePerPiece: 1.51,
    netWeight: 5.2,
    quantity: 28,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_2',
    name: 'lucky me mami spicy labuyo beef',
    cost: 48,
    costPerPiece: 8,
    sellingPricePerPiece: 11,
    netWeight: 50,
    quantity: 6,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_3',
    name: 'lucky me pancit canton extra hot chili',
    cost: 70.8,
    costPerPiece: 11.799999999999999,
    sellingPricePerPiece: 16,
    netWeight: 80,
    quantity: 6,
    expiryDate: '2020-08-21T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_4',
    name: 'lucky me pancit canton sweet and spicy',
    cost: 70.8,
    costPerPiece: 11.799999999999999,
    sellingPricePerPiece: 16,
    netWeight: 80,
    quantity: 6,
    expiryDate: '2020-08-07T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_5',
    name: 'lucky me pancit canton kalamansi flavor',
    cost: 70.8,
    costPerPiece: 11.799999999999999,
    sellingPricePerPiece: 16,
    netWeight: 80,
    quantity: 6,
    expiryDate: '2020-08-04T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_6',
    name: 'lucky me beef noodles',
    cost: 45.6,
    costPerPiece: 7.6000000000000005,
    sellingPricePerPiece: 10,
    netWeight: 55,
    quantity: 6,
    expiryDate: '09/19/2020',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_7',
    name: 'lucky me chicken noodles',
    cost: 45.6,
    costPerPiece: 7.6000000000000005,
    sellingPricePerPiece: 10,
    netWeight: 55,
    quantity: 6,
    expiryDate: '2020-08-21T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_8',
    name: 'great taste white coffee',
    cost: 92.5,
    costPerPiece: 9.25,
    sellingPricePerPiece: 13,
    netWeight: 50,
    quantity: 10,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_9',
    name: 'nescafe original coffee',
    cost: 103.15,
    costPerPiece: 8.595833333333333,
    sellingPricePerPiece: 12,
    netWeight: 48,
    quantity: 12,
    expiryDate: '2021-02-27T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_10',
    name: 'star margarin sweet blend',
    cost: 32,
    costPerPiece: 8,
    sellingPricePerPiece: 11,
    netWeight: 30,
    quantity: 4,
    expiryDate: '2020-12-02T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_11',
    name: 'Super Q Bihon',
    cost: 66.2,
    costPerPiece: 16.55,
    sellingPricePerPiece: 22,
    netWeight: 8,
    quantity: 4,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_12',
    name: 'Angel evaporated milk',
    cost: 41,
    costPerPiece: 20.5,
    sellingPricePerPiece: 25,
    netWeight: 365,
    quantity: 2,
    expiryDate: '2021-01-30T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_13',
    name: 'Alaska evaporated milk',
    cost: 22.4,
    costPerPiece: 11.2,
    sellingPricePerPiece: 15,
    netWeight: 140,
    quantity: 2,
    expiryDate: '2020-10-22T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_14',
    name: 'Alaska condensada sweetened condensed creamer',
    cost: 75.5,
    costPerPiece: 37.75,
    sellingPricePerPiece: 50,
    netWeight: 250,
    quantity: 2,
    expiryDate: '2020-04-07T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_15',
    name: 'Alaska all purpose cream',
    cost: 107.2,
    costPerPiece: 53.6,
    sellingPricePerPiece: 70,
    netWeight: 250,
    quantity: 2,
    expiryDate: '2020-06-19T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_16',
    name: 'Bear brand powder milk',
    cost: 65.8,
    costPerPiece: 16.45,
    sellingPricePerPiece: 21,
    netWeight: 60,
    quantity: 4,
    expiryDate: '2020-01-30T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_17',
    name: 'White Sugar',
    cost: 52.5,
    costPerPiece: 26.25,
    sellingPricePerPiece: 35,
    netWeight: 0.5,
    quantity: 2,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_18',
    name: 'Brown sugar',
    cost: 46,
    costPerPiece: 11.5,
    sellingPricePerPiece: 15,
    netWeight: 0.25,
    quantity: 4,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_19',
    name: 'Argentina corned beef',
    cost: 96,
    costPerPiece: 32,
    sellingPricePerPiece: 42,
    netWeight: 150,
    quantity: 3,
    expiryDate: 'Jan 21 2023',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_20',
    name: '555 tuna Caldereta',
    cost: 46.5,
    costPerPiece: 23.25,
    sellingPricePerPiece: 31,
    netWeight: 155,
    quantity: 2,
    expiryDate: 'Nov.26, 2022',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_21',
    name: '555 hot sardines',
    cost: 53.4,
    costPerPiece: 17.8,
    sellingPricePerPiece: 24,
    netWeight: 155,
    quantity: 3,
    expiryDate: '2022-07-23T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_22',
    name: '555 sardines',
    cost: 52.65,
    costPerPiece: 17.55,
    sellingPricePerPiece: 23,
    netWeight: 155,
    quantity: 3,
    expiryDate: '2022-07-01T16:00:00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_23',
    name: '555 tuna afritada',
    cost: 46.5,
    costPerPiece: 23.25,
    sellingPricePerPiece: 31,
    netWeight: 155,
    quantity: 2,
    expiryDate: 'jan., 10, 2023 ',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_24',
    name: '555 tuna mechado',
    cost: 46.5,
    costPerPiece: 23.25,
    sellingPricePerPiece: 31,
    netWeight: 155,
    quantity: 2,
    expiryDate: [
      'oct.',
      10,
      2021
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_25',
    name: 'san marino corned tuna',
    cost: 123,
    costPerPiece: 30.75,
    sellingPricePerPiece: 40,
    netWeight: 150,
    quantity: 4,
    expiryDate: 'aug..14,2022',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_26',
    name: 'Lorins patis',
    cost: 29.7,
    costPerPiece: 9.9,
    sellingPricePerPiece: 13,
    netWeight: 150,
    quantity: 3,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_27',
    name: 'datu puti soy sauce',
    cost: 18.2,
    costPerPiece: 3.033333333333333,
    sellingPricePerPiece: 5,
    netWeight: 60,
    quantity: 6,
    expiryDate: 'oct., 15, 2020',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_28',
    name: 'datu puti vinegar',
    cost: 17.25,
    costPerPiece: 2.875,
    sellingPricePerPiece: 5,
    netWeight: 60,
    quantity: 6,
    expiryDate: 'aug., 24, 2020',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_29',
    name: 'pineapple tidbits',
    cost: 42.45,
    costPerPiece: 14.15,
    sellingPricePerPiece: 19,
    netWeight: 115,
    quantity: 3,
    expiryDate: 'Jan.,2020',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_30',
    name: 'Mang tomas all around sarsa',
    cost: 30,
    costPerPiece: 10,
    sellingPricePerPiece: 13,
    netWeight: 100,
    quantity: 3,
    expiryDate: [
      10,
      20,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_31',
    name: 'UFC tamis anghang banana catsup',
    cost: 15.5,
    costPerPiece: 7.75,
    sellingPricePerPiece: 11,
    netWeight: 100,
    quantity: 2,
    expiryDate: [
      'oct.',
      19,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_32',
    name: 'UFC tamis anghang banana catsup',
    cost: 13.5,
    costPerPiece: 13.5,
    sellingPricePerPiece: 18,
    netWeight: 200,
    quantity: 1,
    expiryDate: [
      'nov.',
      21,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_33',
    name: 'Delmonte orig.style tomato sauce',
    cost: 31.6,
    costPerPiece: 15.8,
    sellingPricePerPiece: 21,
    netWeight: 115,
    quantity: 2,
    expiryDate: [
      'nov.',
      14,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_34',
    name: 'Delmonte orig.style tomato sauce',
    cost: 19.7,
    costPerPiece: 19.7,
    sellingPricePerPiece: 26,
    netWeight: 200,
    quantity: 1,
    expiryDate: [
      'dec.',
      7,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_35',
    name: 'Milo powder',
    cost: 83.5,
    costPerPiece: 6.958333333333333,
    sellingPricePerPiece: 9,
    netWeight: 24,
    quantity: 12,
    expiryDate: [
      'nov.',
      30,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_36',
    name: 'ajinomoto',
    cost: 47.15,
    costPerPiece: 2.6194444444444445,
    sellingPricePerPiece: 4,
    netWeight: 11,
    quantity: 18,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_37',
    name: 'Sinigang mix sa sampalok orig',
    cost: 128.65,
    costPerPiece: 10.720833333333333,
    sellingPricePerPiece: 14,
    netWeight: 22,
    quantity: 12,
    expiryDate: '2021 - 04 - 15T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_38',
    name: 'Magic sarap mix',
    cost: 74.8,
    costPerPiece: 3.1166666666666667,
    sellingPricePerPiece: 5,
    netWeight: 8,
    quantity: 24,
    expiryDate: [
      'Dec.',
      31,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_39',
    name: 'Knorr cubes(pork)',
    cost: 56,
    costPerPiece: 4.666666666666667,
    sellingPricePerPiece: 7,
    netWeight: 10,
    quantity: 12,
    expiryDate: '2020 - 03 - 31T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_40',
    name: 'Knorr cubes(beef)',
    cost: 56,
    costPerPiece: 4.666666666666667,
    sellingPricePerPiece: 7,
    netWeight: 10,
    quantity: 12,
    expiryDate: [
      '0ct.',
      19,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_41',
    name: 'Knorr cubes (chicken)',
    cost: 56,
    costPerPiece: 4.666666666666667,
    sellingPricePerPiece: 7,
    netWeight: 10,
    quantity: 12,
    expiryDate: [
      ' nov.',
      18,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_42',
    name: 'Vermicelli',
    cost: 35.95,
    costPerPiece: 7.19,
    sellingPricePerPiece: 10,
    netWeight: null,
    quantity: 5,
    expiryDate: [
      'Dec.',
      31,
      2022
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_43',
    name: 'OIL',
    cost: 213,
    costPerPiece: 17.75,
    sellingPricePerPiece: 23,
    netWeight: null,
    quantity: 12,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_44',
    name: 'Marlboro cig.',
    cost: 996,
    costPerPiece: 99.6,
    sellingPricePerPiece: 130,
    netWeight: null,
    quantity: 10,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_45',
    name: 'Mentos',
    cost: 68.75,
    costPerPiece: 0.6875,
    sellingPricePerPiece: 1,
    netWeight: null,
    quantity: 100,
    expiryDate: [
      'Dec.',
      2021
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_46',
    name: 'Bread stix cheese',
    cost: 51.5,
    costPerPiece: 5.15,
    sellingPricePerPiece: 7,
    netWeight: 20,
    quantity: 10,
    expiryDate: 'june 17.2020',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_47',
    name: 'STICK -O jr.choco',
    cost: 52,
    costPerPiece: 1,
    sellingPricePerPiece: 1.5,
    netWeight: 380,
    quantity: 52,
    expiryDate: [
      'sept.', 20,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_48',
    name: 'STICK -O jr.Strawberry',
    cost: 52,
    costPerPiece: 1,
    sellingPricePerPiece: 1.5,
    netWeight: 380,
    quantity: 52,
    expiryDate: [
      'sept.',
      13,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_49',
    name: 'C2 - solo',
    cost: 66,
    costPerPiece: 11,
    sellingPricePerPiece: 15,
    netWeight: 230,
    quantity: 6,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_50',
    name: 'OISHI',
    cost: 18.5,
    costPerPiece: 0.925,
    sellingPricePerPiece: 2,
    netWeight: 18,
    quantity: 20,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_51',
    name: 'Lemon square cheese cake',
    cost: 57,
    costPerPiece: 5.7,
    sellingPricePerPiece: 8,
    netWeight: 300,
    quantity: 10,
    expiryDate: '2020 - 03 - 14T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_52',
    name: 'Iced gem biscuits',
    cost: 73,
    costPerPiece: 6.083333333333333,
    sellingPricePerPiece: 8,
    netWeight: 30,
    quantity: 12,
    expiryDate: [
      'oct.',
      12,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_53',
    name: 'Tattoos corn',
    cost: 11.1,
    costPerPiece: 1,
    sellingPricePerPiece: 1.25,
    netWeight: 10,
    quantity: 12,
    expiryDate: '2020 - 07 - 24T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_54',
    name: 'Potchi strawberry creams',
    cost: 27,
    costPerPiece: 0.54,
    sellingPricePerPiece: 1.84,
    netWeight: 2.7,
    quantity: 50,
    expiryDate: [
      'jan.',
      21,
      2021
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_55',
    name: 'Sugo hot and spicy peanuts',
    cost: 17.6,
    costPerPiece: 1,
    sellingPricePerPiece: 2,
    netWeight: 6,
    quantity: 20,
    expiryDate: '2020 - 07 - 17T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_56',
    name: 'Piattos sour cream and onion',
    cost: 23.2,
    costPerPiece: 11.6,
    sellingPricePerPiece: 12.9,
    netWeight: 40,
    quantity: 2,
    expiryDate: '2020 - 07 - 20T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_57',
    name: 'piattoos cheese jack and jill',
    cost: 23.2,
    costPerPiece: 11.6,
    sellingPricePerPiece: 12.9,
    netWeight: 40,
    quantity: 2,
    expiryDate: '2020 - 07 - 10T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_58',
    name: 'Rinbee cheese sticks',
    cost: 10.4,
    costPerPiece: 5.2,
    sellingPricePerPiece: 6.5,
    netWeight: 24,
    quantity: 2,
    expiryDate: '2020 - 07 - 09T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_59',
    name: 'Mr. chips',
    cost: 9.4,
    costPerPiece: 4.7,
    sellingPricePerPiece: 6,
    netWeight: 26,
    quantity: 2,
    expiryDate: '2020 - 06 - 18T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_60',
    name: 'Dingdong mixed nuts',
    cost: 17.6,
    costPerPiece: 0.8800000000000001,
    sellingPricePerPiece: 2.18,
    netWeight: 5,
    quantity: 20,
    expiryDate: '2020 - 06 - 16T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_61',
    name: 'jelliyum',
    cost: 12.6,
    costPerPiece: 1.05,
    sellingPricePerPiece: 2.35,
    netWeight: 129,
    quantity: 12,
    expiryDate: [
      'sept', 28,
      2020
    ],
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_62',
    name: 'pillows choco filled crackers',
    cost: 14.2,
    costPerPiece: 7.1,
    sellingPricePerPiece: 8.4,
    netWeight: 38,
    quantity: 2,
    expiryDate: '2020 - 08 - 26T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_63',
    name: 'posporo',
    cost: 16.25,
    costPerPiece: 1.625,
    sellingPricePerPiece: 2.925,
    netWeight: null,
    quantity: 10,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_64',
    name: 'gin bilog',
    cost: 154.5,
    costPerPiece: 51.5,
    sellingPricePerPiece: 55,
    netWeight: null,
    quantity: 3,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_65',
    name: 'Emperador light',
    cost: 222,
    costPerPiece: 111,
    sellingPricePerPiece: 120,
    netWeight: 750,
    quantity: 2,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_66',
    name: 'creamsilk conditioner stand out straight',
    cost: 59.35,
    costPerPiece: 4.945833333333334,
    sellingPricePerPiece: 6.245833333333334,
    netWeight: null,
    quantity: 12,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_67',
    name: 'creamsilk conditioner hairfall defense',
    cost: 59.35,
    costPerPiece: 4.945833333333334,
    sellingPricePerPiece: 6.245833333333334,
    netWeight: null,
    quantity: 12,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_68',
    name: 'palmolive natural shampoo intensive moisture',
    cost: 49,
    costPerPiece: 4,
    sellingPricePerPiece: 6,
    netWeight: 15,
    quantity: 12,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_69',
    name: 'sunsilk strong and long',
    cost: 49,
    costPerPiece: 4.083333333333333,
    sellingPricePerPiece: 6,
    netWeight: null,
    quantity: 12,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_70',
    name: 'safeguard pure white',
    cost: 66,
    costPerPiece: 16.5,
    sellingPricePerPiece: 22,
    netWeight: null,
    quantity: 4,
    expiryDate: '2020 - 02 - 26T16: 00: 00.000Z',
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_71',
    name: 'silka whitening herbal soap',
    cost: 49.5,
    costPerPiece: 16.5,
    sellingPricePerPiece: 22,
    netWeight: 65,
    quantity: 3,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_72',
    name: 'surf active clean purple blooms',
    cost: 30,
    costPerPiece: 7.5,
    sellingPricePerPiece: 10,
    netWeight: null,
    quantity: 4,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_73',
    name: ' joy dishwashing liquid calamansi',
    cost: 29.5,
    costPerPiece: 4.916666666666667,
    sellingPricePerPiece: 7,
    netWeight: null,
    quantity: 6,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_74',
    name: 'colgate fresh confidence with cooling crystals',
    cost: 79,
    costPerPiece: 6.583333333333333,
    sellingPricePerPiece: 9,
    netWeight: 22,
    quantity: 12,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_75',
    name: 'pork skinless',
    cost: 90,
    costPerPiece: 45,
    sellingPricePerPiece: 55,
    netWeight: null,
    quantity: 2,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_76',
    name: 'TOCINO',
    cost: 120,
    costPerPiece: 60,
    sellingPricePerPiece: 75,
    netWeight: null,
    quantity: 2,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_77',
    name: 'pork longganisa',
    cost: 90,
    costPerPiece: 45,
    sellingPricePerPiece: 55,
    netWeight: null,
    quantity: 2,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_78',
    name: 'bologna',
    cost: 70,
    costPerPiece: 35,
    sellingPricePerPiece: 45,
    netWeight: null,
    quantity: 2,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_79',
    name: 'star regular hotdog',
    cost: 40,
    costPerPiece: 40,
    sellingPricePerPiece: 50,
    netWeight: null,
    quantity: 1,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_80',
    name: 'star chicken hotdog',
    cost: 40,
    costPerPiece: 40,
    sellingPricePerPiece: 50,
    netWeight: null,
    quantity: 1,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_81',
    name: 'tapa',
    cost: 130,
    costPerPiece: 65,
    sellingPricePerPiece: 80,
    netWeight: null,
    quantity: 2,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_82',
    name: 'yema',
    cost: 50,
    costPerPiece: 0.8333333333333334,
    sellingPricePerPiece: 2,
    netWeight: null,
    quantity: 60,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_83',
    name: 'ube pastillas',
    cost: 50,
    costPerPiece: 1,
    sellingPricePerPiece: 2,
    netWeight: null,
    quantity: 60,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_84',
    name: 'mazapan',
    cost: 55,
    costPerPiece: 3.6666666666666665,
    sellingPricePerPiece: 5,
    netWeight: null,
    quantity: 15,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_85',
    name: 'toasted pastillas',
    cost: 50,
    costPerPiece: 1,
    sellingPricePerPiece: 2,
    netWeight: null,
    quantity: 60,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_86',
    name: 'laurel',
    cost: 25,
    costPerPiece: null,
    sellingPricePerPiece: 1,
    netWeight: null,
    quantity: null,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_87',
    name: 'pamitang buo',
    cost: 25,
    costPerPiece: null,
    sellingPricePerPiece: 1,
    netWeight: null,
    quantity: null,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_88',
    name: 'pamintang durog',
    cost: 25,
    costPerPiece: null,
    sellingPricePerPiece: 1,
    netWeight: null,
    quantity: null,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_89',
    name: 'asin',
    cost: 10,
    costPerPiece: null,
    sellingPricePerPiece: 3,
    netWeight: null,
    quantity: null,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_90',
    name: 'aswete',
    cost: 38,
    costPerPiece: null,
    sellingPricePerPiece: 3,
    netWeight: null,
    quantity: null,
    expiryDate: null,
    image: '',
    description: '',
    status: true,
    barCode: null
  },
  {
    itemCode: 'ITEM_91',
    name: 'Eggs',
    cost: 85,
    costPerPiece: null,
    sellingPricePerPiece: 7,
    netWeight: null,
    quantity: 15,
    expiryDate: null,
    image: '',
    description: '',
    status: null,
    barCode: null
  }
];

